### PR TITLE
upgpkg: ros-noetic-libfranka 0.8.0-1

### PR DESCRIPTION
**Pull request by ruturajsambhusvt**
Changed the pkgver to 0.8.0 and sha256 sum corresponding to the 0.8.0 repository. Don't know if it works, can try any suggestions.

### CODE REVIEW

**Comment by acxz** [comment]
The commit message should be `upgpkg: ros-noetic-libfranka 0.8.0-1` since the format is `upgpkg: <package-name> <pkgver>-<pkgrel>`.

However, why would we want to downgrade the package from 0.9.0 to 0.8.0? Rather shouldn't the other [`ros-noetic-franka-*`](https://aur.archlinux.org/packages?O=0&SeB=nd&K=ros-noetic-franka&outdated=&SB=p&SO=d&PP=50&submit=Go) packages be updated to 0.9.0?

**Comment by ruturajsambhusvt** [comment]
Got it! Sorry, it is my first pull on Github. I have libfranka C++ version of 0.8.0 which works well and cannot be updated since it depends on the hardware. I have tried with 0.9.0 and it doesn't work. Hence, I think that it might not be a good decision to try working with 0.9.0 and I would prefer 0.8.0. I think that depending on their hardware, people would need different versions probably.

**Comment by acxz** [comment]
> it is my first pull on Github

That's great!!

You can change the commit message with the `git commit --amend` command. Change the title of the PR won't do the trick ;)

**Comment by ruturajsambhusvt** [comment]
Updated the commit name!

**Comment by acxz** [comment]
> I have tried with 0.9.0 and it doesn't work.

Maybe you can post an issue about it upstream (https://github.com/frankaemika/libfranka), they will probably know what to do to fix it, since they write the package. Feel free to mention me as well, I may be able to help out if it is something simple enough. 

> Hence, I think that it might not be a good decision to try working with 0.9.0 and I would prefer 0.8.0.

Understandable, however, as you can imagine maintaining older versions can be a larger maintenance burden for us and a strong philosophy of Arch is to stay up to date and close to upstream as possible. You can however, use the PKGBUILD you just created for your purposes. You can install it with a `makepkg -i`, but I don't want to downgrade the package that other potential libfranka users might be using.

If this is truly a hardware issue, then the only solution would be to have your own 0.8.0 package to work with.

**Comment by acxz** [comment]
Here is the difference between https://github.com/frankaemika/libfranka/compare/0.8.0...0.9.0
 and here is the [changelog](https://github.com/frankaemika/libfranka/blob/master/CHANGELOG.md), looks like there are some breaking changes that you may need to be aware of when upgrading b/t 0.8.0 to 0.9.0

**Comment by ruturajsambhusvt** [comment]
I get your point! Thank you so much for helping. I tried to use the package build using makepkg -i and it still throws errors.

**Comment by acxz** [comment]
I'm afraid I won't help you debug issues for trying to get an older versions working, but again feel free to post the issues you face with the latest stable version.

**Comment by ruturajsambhusvt** [comment]
Hello, I checked out and it won't be possible to use 0.9.0 for my hardware as per manufacturer specs. Thank you for your support though!

**Comment by acxz** [comment]
@ruturajsambhusvt you can post your issue actually, since there is nothing you can do if it is a hardware issue. I'll help debug.

**Comment by ruturajsambhusvt** [comment]
Thank you very much! I will continue on the previous issue or make a new one? Or I should still post upstream (https://github.com/frankaemika/libfranka)?

**Comment by acxz** [comment]
We can continue the conversation on a new issue if you don't mind. We'll post upstream once we know that it is not an archlinux packaging problem.

**Pull request closed without merging**
